#!/usr/bin/env php
<?php
require __DIR__."/vendor/autoload.php";
use Symfony\Component\Console\Application;

$application = new Application("Link current project as a composer package. \nYou need administrator privilege to run this command.", "1.0.0");
$application->add(new LinkCommand());
$application->run();